<h1><?php // echo $block->getTitle(); 
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $cookieManager = $objectManager->get('Magento\Framework\Stdlib\CookieManagerInterface');

            //get cookie value
            // $customeZ = $cookieManager->setPublicCookie('customeZ', 'customeZi');
            // $customeZ = $cookieManager->getCookie('customeZ');
            // $customeZip = $cookieManager->getCookie('customerZipSet');

    ?></h1>
<?php //{{block class="Knowarth\Zipcode\Block\CheckZip" name="lofformbuilder-toplinks" template="Knowarth_Zipcode::checkzip.phtml"}} ?>
<?php 
    // $zip = $this->getSessionData('zip');
    if(empty($cookieManager->getCookie('customerZipSet'))){
    ?>
    <div id="popup-mpdal">
    <form action="#" method="post" id="zipform" name ="zipform">
        <input name = "zipcode" type="text" placeholder="zipcode">
        <input id="formsubmit" name = "zipsubmit" type="button" value="submit" >
    </form>
</div>
    <?php   }  ?>
    <script>
        require(['jquery'], function($) {

            $(document).ready(function($) {

                $( "#formsubmit" ).click(function() {
                    var data = $('#zipform').serialize();
                    // alert(data);
                    // console.log(data);
                    jQuery.ajax({
                        url:'<?php  echo $this->getBaseUrl()."knowarth_zipcode/check/zip/"; ?>',
                        type:'POST',
                        data: data,
                        showLoader:true,
                        // beforeSend:function()
                        // {
                            // jQuery('.loader').show();
                        // },
                        success: function(response)
                        {
                            if(response.success == true){
                                document.cookie="customerZipSet=customerZipSet";
                                // $('#popup-mpdal').closeModal();
                                $('#popup-mpdal').modal('closeModal')
                            // var cookieValue = document.cookie;
                            // alert(cookieValue);
                            }
                            else {
                                alert("Invalid Zipcode");
                            }
                            // alert(response.success);
                        }
                    });
                });

            });
        });
    </script>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Enter',
                buttons: []
            };

            var popup = modal(options, $('#popup-mpdal'));

            $('#popup-mpdal').modal('openModal');
        }
    );
</script>